# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "culerity"
  s.version = "0.2.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Lang"]
  s.date = "2010-06-28"
  s.default_executable = %q{run_celerity_server.rb}
  s.description = %q{Culerity integrates Cucumber and Celerity in order to test your application's full stack.}
  s.email = %q{alex@upstream-berlin.com}
  s.executables = ["run_celerity_server.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = Dir.glob([
    ".gitignore",
     "CHANGES.md",
     "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "bin/run_celerity_server.rb",
     "init.rb",
     "lib/**/*.rb",
     "rails/**/*.rb",
     "rails_generators/**/*",
     "script/*"
  ])
  s.homepage = %q{http://github.com/langalex/culerity}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Culerity integrates Cucumber and Celerity in order to test your application's full stack.}
  s.test_files = Dir.glob([
    "features/**/*.feature",
    "features/**/*.rb",
    "features/fixtures/*",
    "spec/**/*.rb"
  ])

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency("cucumber-rails", [">= 0"])
      s.add_development_dependency("rspec", [">= 0"])
    else
      s.add_dependency('cucumber-rails', [">= 0"])
      s.add_dependency('rspec', [">= 0"])
    end
  else
    s.add_dependency('cucumber-rails', [">= 0"])
    s.add_dependency('rspec', [">= 0"])
  end
end

